import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/hooks/useTheme";
import ToggleThemeButton from "@/components/ui/ToggleThemeButton";
import { geistMono, geistSans } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="absolute top-1 right-1">
            <ToggleThemeButton />
          </div>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
